replicaCount: 2

image:
  repository: ruby_server
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

nameOverride: "ruby-server"
fullnameOverride: "ruby-server"

serviceAccount:
  create: true
  name: "ruby-server-sa"

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  hosts:
    - host: ruby-server.local
      paths:
        - path: /
          pathType: ImplementationSpecific

host: ruby-server.local

resources:
  requests:
    cpu: "250m"
  limits:
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
  targetMemoryUtilizationPercentage: 80

namespace: "ruby-server"