apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-ruby-chart.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
{{ include "simple-ruby-chart.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "simple-ruby-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}